version: "3.9"

services:
  api:
    build: ./api
    container_name: ecommerce_api
    volumes:
      - ./db:/data
    environment:
      - DB_PATH=/data/app.db
    ports:
      - "8000:8000"

  ui:
    build: ./ui
    container_name: ecommerce_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
